### ISSUE TITLE
Player List - With Accents

### ISSUE THREAD

**Issue by Dermotron** [archibalduk/TransferTool#10]
hi guys,

The Player Lists (NO ACCENTS) is really handy. Could the same be made with accents? Saves having to convert a file before matching it to the DB

**Comment by MScientistCM** [comment]
done, can be tested when i publish next release

**Comment by MScientistCM** [comment]
I totally forgot to publish this @Dermotron . Published now in [v1.1.4](https://github.com/archibalduk/TransferTool/releases/tag/v1.1.4)
