### ISSUE TITLE
Clubs Importer

### ISSUE THREAD

**Issue by MScientistCM** [archibalduk/TransferTool#7]
clubs are the nucleus of the all the data in the Database e.g. Club Rep determines a players Current Rep. The Division a club is in determines a players Current Ability range.

Then there is all the tedious, but necessary, work like final positions, updating club reps, cash values. From what I gather Division can't be changed via an import or that it's too dodgy. That would be a "nice to have" rather than a "must have" - it's probably from a process point of view better done in the Editor as a relegated team is -1 Club Rep and a promoted club is +1 Club Rep.

**Comment by Dermotron** [comment]
Is it possible to import new clubs with this tool Gian?

**Comment by MScientistCM** [comment]
> 
> 
> Is it possible to import new clubs with this tool Gian?

No, as of now you can only import existing clubs. But can be doable if useful.

**Comment by Dermotron** [comment]
I figured out a dirty bodge, I used JohnLocke's old club parser to import clubs. For some reason it throws out the national team coaches e.g. for every 1 club added, the national team manager was out of sync by 1.  I then restored the correct order from a backup
